name: Post Dependencies To Confluence
description: Replace a Confluence page with the list of dependencies provided as input
inputs:
  dependencies:
    description: 'Dependencies for the service to update the wiki with'
    required: true
  confluence-url:
    description: 'The URL to the Confluence wiki to update'
    required: true
  confluence-user:
    description: 'The username to use for authentication against Confluence'
    required: true
  confluence-token:
    description: 'The API token to use for authentication against Confluence'
    required: true
  confluence-content-id:
    description: 'The ID of the content page to update'
    required: true

runs:
  using: node16
  main: lib/index.js
